name: Setup environment

inputs:
  python-version:
    description: 'Python version'
    required: false
    default: 3.8.12

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Cache poetry virtualenv
      uses: actions/cache@v3
      id: cached-poetry-dependencies
      with:
        path: .venv
        key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('poetry.lock') }}

    - name: Install python dependencies
      shell: bash
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install
