name: Setup poetry

inputs:
  python-version:
    description: 'Python version'
    required: false
    default: 3.8.12
  poetry-version:
    description: 'Poetry version'
    required: false
    default: latest

runs:
  using: 'composite'
  steps:
    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install poetry
      uses: snok/install-poetry@v1
      with:
        version: ${{ inputs.poetry-version }}
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
