name: Style

on: workflow_call

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup environment with Poetry
        uses: ./.github/actions/setup-environment

      - name: Format with black
        run: |
          poetry run black --diff --check .
