name: Setup environment with Poetry

on: workflow_call

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup environment with Poetry
        uses: ./.github/actions/setup-environment
