name: Unit-test

on: workflow_call

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup environment with Poetry
        uses: ./.github/actions/setup-environment

      - name: Test with pytest
        run: poetry run pytest
