name: Shell checks

on: workflow_call

jobs:
  sh-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run sh-checker
        uses: luizm/action-sh-checker@master
        env:
          SHFMT_OPTS: -i 2
        with:
          sh_checker_exclude: |
            '^cov_html/ ^data/ ^hooks/ ^runs/ ^src/ ^submodules/ ^tests/'
