# Adapted from: https://github.com/zenml-io/zenml
# Adapted from: https://luminousmen.com/post/making-ci-workflow-faster-with-github-actions

name: Static analysis

on:
  workflow_dispatch:
  pull_request:
    branches: main
    paths: ['src/**', 'notebooks/**', 'tests/**', 'pyproject.toml', 'poetry.lock', '.flake8',
    'scripts/**', '.github/actions/setup-poetry/action.yml', '.github/workflows/static.yml']
  push:
    branches: main
    paths: ['src/**', 'notebooks/**', 'tests/**', 'pyproject.toml', 'poetry.lock', '.flake8',
    'scripts/**', '.github/actions/setup-poetry/action.yml', '.github/workflows/static.yml']

concurrency:
  # new commit on branch cancels running workflows of the same branch
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup poetry
        uses: ./.github/actions/setup-poetry

      - name: Cache poetry virtualenv
        uses: actions/cache@v3
        id: cache-dev
        with:
          path: .venv
          key: dev-${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('poetry.lock') }}

      - name: Install dependencies
        if: steps.cache-dev.outputs.cache-hit != 'true'
        run: |
          poetry install --only dev

      - name: Python style-check with black
        run: |
          poetry run black --diff --check .

      - name: Python import-check with isort
        run: |
          poetry run isort --diff --check-only .

      - name: Python lint with flake8
        run: |
          poetry run flake8 --show-source --statistics .

      - name: Ipynb style-check with black
        run: |
          poetry run nbqa black --diff --check .

      - name: Ipynb import-check with isort
        run: |
          poetry run nbqa isort --diff --check-only .

      - name: Ipynb lint with flake8
        run: |
          poetry run nbqa flake8 --show-source --statistics .

      - name: Style-check with shfmt
        run: |
          poetry run bash -c 'find ./scripts -type f -print0 | xargs -0 shfmt -i 2 -d'

      - name: Lint with shellcheck
        run: |
          poetry run bash -c 'find ./scripts -type f -print0 | xargs -0 shellcheck'
